//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk_Work.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitigationStrategies
    {
        public int StrategyID { get; set; }
        public int RiskID { get; set; }
        public string StrategyName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
    
        public virtual Risks Risks { get; set; }
    }
}
