//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk_Work.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiskBDEntities : DbContext
    {
        private static RiskBDEntities _context;

        public static RiskBDEntities GetContext()
        {
            if(_context == null)
                _context = new RiskBDEntities();
            return _context;
        }
        public RiskBDEntities()
            : base("name=RiskBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MitigationStrategies> MitigationStrategies { get; set; }
        public virtual DbSet<RiskAssessments> RiskAssessments { get; set; }
        public virtual DbSet<RiskCategories> RiskCategories { get; set; }
        public virtual DbSet<RiskLevels> RiskLevels { get; set; }
        public virtual DbSet<Risks> Risks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
