//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk_Work.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessments
    {
        public int AssessmentID { get; set; }
        public int RiskID { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public int LevelID { get; set; }
    
        public virtual RiskLevels RiskLevels { get; set; }
        public virtual Risks Risks { get; set; }
    }
}
