//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk_Work.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Risks()
        {
            this.MitigationStrategies = new HashSet<MitigationStrategies>();
            this.RiskAssessments = new HashSet<RiskAssessments>();
        }
    
        public int RiskID { get; set; }
        public string RiskName { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public Nullable<double> Probability { get; set; }
        public Nullable<double> Impact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MitigationStrategies> MitigationStrategies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAssessments> RiskAssessments { get; set; }
        public virtual RiskCategories RiskCategories { get; set; }
    }
}
